spring:
  datasource:
      hikari:
        jdbc-url: jdbc:h2:tcp://localhost/~/Projects/JPA1/jpa1
        username: sa
        password:
        driver-class-name: org.h2.Driver

  jpa:
    hibernate:
       ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql : debug


